### ISSUE TITLE
Shaking in mirror clone of World Constrained prop

### ISSUE THREAD

**Issue by Protected** [VRLabs/VRChat-Avatars-3.0#1]
Example video [here](https://www.myshelter.net/worldconstraint.mp4).

This is just a regular prop using your world constraint method. Did I mess up, or is this expectable? Anything I can do to fix it? Thanks!

**Comment by oofdesu** [comment]
> Example video [here](https://www.myshelter.net/worldconstraint.mp4).
> 
> This is just a regular prop using your world constraint method. Did I mess up, or is this expectable? Anything I can do to fix it? Thanks!

You should expect mirror jitter with this constraint method. It's only present for you locally. Remote players don't see it. The VRChat mirror behavior would have to change in order to fix this. Hopefully they will have something native soon.

**Comment by Protected** [comment]
Thanks for the information!
