### ISSUE TITLE
GrabFX transform issue

### ISSUE THREAD

**Issue by Crecross** [VRLabs/VRChat-Avatars-3.0#3]
https://user-images.githubusercontent.com/29289083/121679698-7c43db80-ca6d-11eb-95dc-afb1be001481.mp4

**Comment by RetroGEO** [comment]
Change the transform from "center" to "pivot."

**Comment by Crecross** [comment]
This happens no matter what I have the mode in..Yet it happens to nothing else in my project, only the GrabFX prefab.

**Comment by oofdesu** [comment]
You must move the child object (#Default) outside of the numbered parent before adjusting the transform. It can go anywhere else in your hierarchy. I have updated the install notes to make this more clear.
