### ISSUE TITLE
GrabFX not working ?

### ISSUE THREAD

**Issue by Kiritosblade** [VRLabs/VRChat-Avatars-3.0#4]
I've followed instructions and also messed around after the fact to figure out what's wrong, discovered my fx controller had no base layer and fixed that then ran Fix Order again and still not working.
My prop is in the default state, i set a menu button to change the value for right and left to try and force it into my hand but still no luck.
Everything seems correct yet i've still got no way to interact with my objects nor do the values change in debug window when i do anything to the object.

**Comment by Kiritosblade** [comment]
![image](https://user-images.githubusercontent.com/9027884/126151839-d7a870db-bb87-4ae7-97ea-c45003bcefd2.png)

**Comment by oofdesu** [comment]
your hierarchy looks correct, can you post your FX controller layers and parameters, and also the parameters in your parameter asset? screenshot of the in-game debug menu would also be helpful
